from .ConstantsAndParameters import *

# useful functions
def w2f(wlen):
    return c0/wlen # returns the frequency [Hz] \\tfrom the wavelength [m]

def f2w(freq):
    return c0/freq # returns the wavelength [m] \\tfrom the frequency [Hz]

def print_const(normalized = False):
    if not normalized:
        print("CONSTANTS and PARAMETERS")
        print()
        print("general physics constants")
        print("ε0\t= %.8e"%ε0, "[F/m] \tvacuum permittivity")
        print("c0\t= %d"%c0, "[m/s] \tspeed of light in vacuum")
        print("ħ\t= %.8e"%ħ, "[J*s] \tPlanck constant")
        print()
        print("geometrical parameters")
        print("R\t= %.2e"%R, "[m ] \tradius")
        print("w\t= %.2e"%w, "[m ] \twidth")
        print("h\t= %.2e"%h, "[m ] \theight")
        print("wga\t= %.2e"%wga, "[m²] \tcore area")
        print()
        print("L\t= %.4e"%L, "[m ] \tcore length")
        print("V\t= %.4e"%V, "[m³] \tcore volume")
        print("Veff\t= %.4e"%Veff, "[m³] \teffective core volume")
        print("Γ\t= %.2f"%Γ, "[1 ] \t\tmodal confinement factor")
        print()
        print("EM field parameters")
        print("λ0\t= %.4e"%λ0, "[m] \tresonance wavelength")
        print("ω0\t= %.4e"%ω0, "[Hz] \tresonance frequency")
        print("λp\t= %.4e"%λp, "[m] \tpump wavelength")
        print("ωp\t= %.4e"%ωp, "[Hz] \tpump frequency")
        print()
        print("Ep\t= %.4e"%Ep, "[√W] \tsquare of EM field power")
        print("Es\t= %.4e"%Es, "[√W] \tsquare of EM field power")
        print()
        print("Silicon physical parameters")
        print("ρSi\t= %.4e"%ρSi, "[kg/m³] \tSilicon density")
        print("Mring\t= %.4e"%Mring, "[kg] \tmass of the microring")
        print("Cp\t= %.2e"%Cp, "[J/kg/K] \tSilicon specific heat at constant pressure")
        print("MCp\t= %.3e"%MCp, "[mW/ω0/K] \tMring*Cp")
        print()
        print("𝛾TH\t= %.3e"%𝛾TH, "[Hz] \tphenomenological heat loss rate")
        print("𝛾FC\t= %.3e"%𝛾FC, "[Hz] \tphenomenological free carrier population loss rate")
        print()
        print("nSi\t= %.3f"%nSi, "[1] \t\tSilicon refractive index")
        print("n0\t= %.3f"%n0, "[1] \t\tdefault system refractive index")
        print("n2\t= %.3e"%n2, "[m²/W] \tSilicon intensity dependent refractive index")
        print("dndT\t= %.3e"%dndT, "[1/K] \tSilicon refractive index expansion term in temperature")
        print("dndN\t= %.3e"%dndN, "[m³] \tSilicon refractive index real expansion term in free carrier population")
        print("dαdN\t= %.3e"%dαdN, "[m²] \tSilicon refractive index imaginary expansion term in free carrier population")
        print("βtpa\t= %.3e"%βtpa, "[m/W] \tSilicon TPA coefficient")
        print("vg\t= %d"%vg, "[m/s] \tgroup velocity near ω0")
        print()
        print("Coupling parameters")
        print("ĸa\t= %.2f"%κa, "[1] \t\tfirst coupling constant")
        print("ĸb\t= %.2f"%κb, "[1] \t\tsecond coupling constant")
        print("τa\t= %.3e"%τa, "[s] \tfirst extrinsic time constant")
        print("τb\t= %.3e"%τb, "[s] \tsecond extrinsic time constant")
        print("τb\t= %.3e"%τb, "[s] \tintrinsic time constant")
    else:
        print("CONSTANTS and PARAMETERS")
        print()
        print("general physics constants* (*not-normalized)")
        print("ε0\t= %.8e"%ε0, "[F/m] \tvacuum permittivity")
        print("c0\t= %d"%c0, "[m/s] \tspeed of light in vacuum")
        print("ħ\t= %.8e"%ħ, "[J*s] \tPlanck constant")
        print()
        print("geometrical parameters")
        print("R\t= %.5f"%ñR, "[λ0 ] \tradius")
        print("w\t= %.5f"%ñw, "[λ0 ] \twidth")
        print("h\t= %.5f"%ñh, "[λ0 ] \theight")
        print("wga\t= %.5f"%ñwga, "[λ0²] \tcore area")
        print()
        print("L\t= %.5f"%ñL, "[λ0 ] \tcore length")
        print("V\t= %.5f"%ñV, "[λ0³] \tcore volume")
        print("Veff\t= %.5f"%ñVeff, "[λ0³] \teffective core volume")
        print("Γ\t= %.2f"%Γ, "[1 ] \t\tmodal confinement factor")
        print()
        print("EM field parameters")
        print("λ0\t= %d"%ñλ0, "[λ0] \t\tresonance wavelength")
        print("ω0\t= %d"%ñω0, "[ω0] \t\tresonance frequency")
        print("λp\t= %.5f"%ñλp, "[λ0] \t\tpump wavelength")
        print("ωp\t= %.5f"%ñωp, "[ω0] \t\tpump frequency")
        print()
        print("Ep\t= %.5f"%ñEp, "[√mW] \tsquare of EM field power")
        print("Es\t= %.5f"%ñEs, "[√mW] \tsquare of EM field power")
        print()
        print("Silicon physical parameters")
        print("ρSi\t= %.4e"%ρSi, "[kg/m³] \tSilicon density")
        print("Mring\t= %.4e"%ñMring, "[kg] \tmass of the microring")
        print("Cp\t= %.2e"%ñCp, "[mW/ω0/kg/K] Silicon specific heat at constant pressure")
        print("MCp\t= %.3e"%ñMCp, "[mW/ω0/K] \tMring*Cp")
        print()
        print("𝛾TH\t= %.3e"%ñ𝛾TH, "[ω0] \tphenomenological heat loss rate")
        print("𝛾FC\t= %.3e"%ñ𝛾FC, "[ω0] \tphenomenological free carrier population loss rate")
        print()
        print("nSi\t= %.3f"%nSi, "[1] \t\tSilicon refractive index")
        print("n0\t= %.3f"%ñn0, "[1] \t\tdefault system refractive index")
        print("n2\t= %.3e"%ñn2, "[λ0²/mW] \tSilicon intensity dependent refractive index")
        print("dndT\t= %.3e"%ñdndT, "[1/K] \tSilicon refractive index expansion term in temperature")
        print("dndN\t= %.3e"%ñdndN, "[λ0³] \tSilicon refractive index real expansion term in free carrier population")
        print("dαdN\t= %.3e"%ñdαdN, "[λ0²] \tSilicon refractive index imaginary expansion term in free carrier population")
        print("βtpa\t= %.3e"%ñβtpa, "[λ0/mW] \tSilicon TPA coefficient")
        print("vg\t= %.3f"%ñvg, "[λ0*ω0] \tgroup velocity near ω0")
        print()
        print("Coupling parameters")
        print("ĸa\t= %.3f"%κa, "[1] \t\tfirst coupling constant")
        print("ĸb\t= %.3f"%κb, "[1] \t\tsecond coupling constant")
        print("τa\t= %.5f"%ñτa, "[1/ω0] \tfirst extrinsic time constant")
        print("τb\t= %.5f"%ñτb, "[1/ω0] \tsecond extrinsic time constant")
        print("τb\t= %.5f"%ñτb, "[1/ω0] \tintrinsic time constant")